In [1]:
import sys, os
is_conda = os.path.exists(os.path.join(sys.prefix, 'conda-meta'))
print(is_conda)

True


In [10]:
import torch
import torchtext
from torchtext.vocab import GloVe

# The first time you run this will download a ~823MB file
glove = GloVe(name="6B", # trained on Wikipedia 2014 corpus
                              dim=50)    # embedding size = 50

100%|█████████▉| 399999/400000 [00:13<00:00, 30690.20it/s]


In [16]:
king = glove['king']
king

tensor([ 0.5045,  0.6861, -0.5952, -0.0228,  0.6005, -0.1350, -0.0881,  0.4738,
        -0.6180, -0.3101, -0.0767,  1.4930, -0.0342, -0.9817,  0.6823,  0.8172,
        -0.5187, -0.3150, -0.5581,  0.6642,  0.1961, -0.1349, -0.1148, -0.3034,
         0.4118, -2.2230, -1.0756, -1.0783, -0.3435,  0.3350,  1.9927, -0.0423,
        -0.6432,  0.7113,  0.4916,  0.1675,  0.3434, -0.2566, -0.8523,  0.1661,
         0.4010,  1.1685, -1.0137, -0.2158, -0.1515,  0.7832, -0.9124, -1.6106,
        -0.6443, -0.5104])

In [18]:
queen = glove['queen']
queen

tensor([ 0.3785,  1.8233, -1.2648, -0.1043,  0.3583,  0.6003, -0.1754,  0.8377,
        -0.0568, -0.7580,  0.2268,  0.9859,  0.6059, -0.3142,  0.2888,  0.5601,
        -0.7746,  0.0714, -0.5741,  0.2134,  0.5767,  0.3868, -0.1257,  0.2801,
         0.2813, -1.8053, -1.0421, -0.1926, -0.5537, -0.0545,  1.5574,  0.3930,
        -0.2475,  0.3425,  0.4536,  0.1624,  0.5246, -0.0703, -0.8374, -1.0326,
         0.4595,  0.2530, -0.1784, -0.7340, -0.2002,  0.2347, -0.5609, -2.2839,
         0.0093, -0.6028])

In [19]:
man = glove['man']
woman = glove['woman']

In [20]:
torch.cosine_similarity(king.unsqueeze(0),
                        queen.unsqueeze(0))

tensor([0.7839])

In [21]:
torch.cosine_similarity(king.unsqueeze(0),
                        man.unsqueeze(0))

tensor([0.5309])

In [22]:
torch.cosine_similarity(king.unsqueeze(0),
                        woman.unsqueeze(0))

tensor([0.4113])

In [23]:
torch.cosine_similarity(man.unsqueeze(0),
                        woman.unsqueeze(0))

tensor([0.8860])

In [24]:
torch.cosine_similarity(man.unsqueeze(0),
                        queen.unsqueeze(0))

tensor([0.5367])

In [25]:
def print_closest_words(vec, n=5):
    dists = torch.norm(glove.vectors - vec, dim=1)     # compute distances to all words
    lst = sorted(enumerate(dists.numpy()), key=lambda x: x[1]) # sort by distance
    for idx, difference in lst[1:n+1]: 					       # take the top n
        print(glove.itos[idx], difference)

In [28]:
import gensim.downloader as api

# Load the GloVe model
model = api.load("glove-wiki-gigaword-50")

# Use the model
result = model.most_similar(positive=["king", "woman"], negative=["man"])

[==================================================] 100.0% 66.0/66.0MB downloaded


In [29]:
result

[('queen', 0.8523604273796082),
 ('throne', 0.7664334177970886),
 ('prince', 0.7592144012451172),
 ('daughter', 0.7473882436752319),
 ('elizabeth', 0.7460219860076904),
 ('princess', 0.7424570322036743),
 ('kingdom', 0.7337412238121033),
 ('monarch', 0.721449077129364),
 ('eldest', 0.7184861898422241),
 ('widow', 0.7099431157112122)]

In [30]:
java_queenish = [0.67332006, -1.22644, -0.033339977, -0.776456, 0.63450104, 0.031590015, 0.90885997, 0.58699, -0.328561, -0.65879005, 0.13019899, 0.41653502, -0.24564996, -0.5697498, -0.023230001, 0.19263, 0.38347697, 0.206045, 1.08172, -1.80633, -0.21172997, 1.1398296, -0.13005996, -0.13892204, -0.06323999, -1.7328999, 0.71458596, -0.14240003, 0.670912, 0.57420003, 3.249, 0.37259, -1.069703, -0.55513, -0.44287, -0.40933004, 0.065400004, -1.1972201, -0.607821, 0.19806999, -0.47261, 0.5765767, 0.19757998, 0.13513005, -0.021974027, -0.669463, -1.4616699, -0.82707, -0.54992, 0.82176006]

In [35]:
import numpy as np
model.similar_by_vector(np.array(java_queenish))

[('demands', 0.7326132655143738),
 ('actions', 0.7286003232002258),
 ('demanding', 0.7265394926071167),
 ('should', 0.7254478931427002),
 ('intervene', 0.7245380878448486),
 ('force', 0.7233016490936279),
 ('must', 0.7194575071334839),
 ('demanded', 0.7173727750778198),
 ('cannot', 0.714293360710144),
 ('not', 0.7124378085136414)]

In [37]:
model['king']

array([ 0.50451 ,  0.68607 , -0.59517 , -0.022801,  0.60046 , -0.13498 ,
       -0.08813 ,  0.47377 , -0.61798 , -0.31012 , -0.076666,  1.493   ,
       -0.034189, -0.98173 ,  0.68229 ,  0.81722 , -0.51874 , -0.31503 ,
       -0.55809 ,  0.66421 ,  0.1961  , -0.13495 , -0.11476 , -0.30344 ,
        0.41177 , -2.223   , -1.0756  , -1.0783  , -0.34354 ,  0.33505 ,
        1.9927  , -0.04234 , -0.64319 ,  0.71125 ,  0.49159 ,  0.16754 ,
        0.34344 , -0.25663 , -0.8523  ,  0.1661  ,  0.40102 ,  1.1685  ,
       -1.0137  , -0.21585 , -0.15155 ,  0.78321 , -0.91241 , -1.6106  ,
       -0.64426 , -0.51042 ], dtype=float32)